### ISSUE TITLE
Issues with fixed elements (update docs)

### ISSUE THREAD

**Issue by LeoSeyers** [ashthornton-gc/asscroll#7]
Hello,
I had to adapt my code to make it work, probably it would be great to add it to the documentation.
This following code did not work initially, I had to wrap it within another div to resolve the issue. 

``` html
<div class="asscroll-container">
  <nav style="position:fixed;"></nav>
  <main> /* content /*</main>
</div>
```

**Comment by LeoSeyers** [comment]
And fixed elements inside won't work properly either. It make sense to pull them out obviously but other people will likely have this issue if it's not documented.

``` html
<nav style="position:fixed;"></nav>
<div class="asscroll-container"> 
  <div class="asscroll-inner"> /* y translation is applied to this first div insider the container */
    <main> /* content /*</main>
    <footer></footer>
  </div>
</div>
```

**Comment by ashthornton-gc** [comment]
Fixed in https://github.com/ashthornton-gc/asscroll/commit/4934cf161011369a360ba381da91cc8c5d8f9824
