### ISSUE TITLE
Provide defaults for Initialisation 

### ISSUE THREAD

**Issue by LeoSeyers** [ashthornton-gc/asscroll#8]
Hi,
Sorry another issue, hope you're doing good.
I tried initializing the lib only with one property, assuming the other options would fall back to default but it did not.

``` js
const smoothScroll = new ASScroll({
      customScrollbar: true
    })
    smoothScroll.enable()
```

`e.js:50 Uncaught TypeError: Cannot read property 'nodeType' of null`

If I had element: '.asscroll-container',   I got `e.js:50 Uncaught TypeError: Cannot read property 'nodeType' of null`

**Comment by ashthornton-gc** [comment]
Fixed in https://github.com/ashthornton-gc/asscroll/commit/0884a06f964e5c3842d8f91342a57bd6228e869e
